[build]
  publish = "frontend"
  functions = "netlify/functions"

# Declare external modules needed by functions
[functions]
  node_bundler = "esbuild"
  # Specify dependencies needed by *all* functions (or use per-function config)
  # external_node_modules = ["axios", "@supabase/supabase-js", "uuid", "openai"]

# Configuration specific for generate-start
[functions."generate-start"]
  external_node_modules = ["axios", "@supabase/supabase-js", "uuid"]

# Configuration specific for get-processed-recipe
[functions."get-processed-recipe"]
  external_node_modules = ["@supabase/supabase-js"]

# Configuration specific for triggerIngredientImageGeneration
[functions."triggerIngredientImageGeneration"]
  memory = 512 # Set memory to 512MB

# Keep the redirects rule (This is needed for frontend calls like /api/generate-start)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
